import React, { useMemo, useState } from "react";
import "./styles/Reports.css";

const REPORT_TYPES = [
  { key: "sales", label: "Sales Report" },
  { key: "expense", label: "Expense Report" },
  { key: "pipeline", label: "Pipeline Report" },
  { key: "team", label: "Team Report" },
  { key: "custom", label: "Custom Report" },
];

const QUICK_REPORTS = [
  { title: "Monthly Sales Summary", subtitle: "Total sales, win rate, top performers" },
  { title: "Pipeline Health Check", subtitle: "Stage-wise analysis, velocity, bottlenecks" },
  { title: "Expense Analysis", subtitle: "Category breakdown, ROI, trends" },
  { title: "Lead Source Performance", subtitle: "Conversion rates by source, best channels" },
  { title: "Activity Report", subtitle: "Calls, emails, meetings, follow-up adherence" },
];

const RECENT_REPORTS = [
  { title: "January Sales Report", by: "Generated by AbhinavDCS", time: "2 hours ago" },
  { title: "Q4 Pipeline Analysis", by: "Generated by AbhinavDCS", time: "Yesterday" },
];

function Reports() {
  const [activeType, setActiveType] = useState("sales");
  const [aiPrompt, setAiPrompt] = useState("");
  const [reportType, setReportType] = useState("Sales Performance");
  const [timePeriod, setTimePeriod] = useState("This Month");
  const [format, setFormat] = useState("PDF");

  const assistantPlaceholder = useMemo(
    () => "E.g., 'Show me deals closed last month in solar sector' or 'Which rep has the best win rate?'",
    []
  );

  return (
    <div className="reports-page">
      <div className="report-type-row">
        {REPORT_TYPES.map((type) => (
          <button
            key={type.key}
            type="button"
            className={`report-type-btn ${activeType === type.key ? "active" : ""}`}
            onClick={() => setActiveType(type.key)}
          >
            {type.label}
          </button>
        ))}
      </div>

      <section className="reports-card">
        <h2 className="reports-card-title">AI Report Assistant</h2>
        <div className="assistant-box">
          <label htmlFor="ai-report-question" className="assistant-label">
            Ask a question in natural language:
          </label>
          <input
            id="ai-report-question"
            type="text"
            value={aiPrompt}
            onChange={(e) => setAiPrompt(e.target.value)}
            placeholder={assistantPlaceholder}
            className="assistant-input"
          />
          <button type="button" className="primary-gradient-btn">
            Generate Report
          </button>
        </div>
      </section>

      <section className="report-grid">
        <div className="reports-card">
          <h2 className="reports-card-title">Quick Reports</h2>
          <div className="quick-report-list">
            {QUICK_REPORTS.map((report) => (
              <button type="button" key={report.title} className="quick-report-item">
                <div className="quick-report-title">{report.title}</div>
                <div className="quick-report-subtitle">{report.subtitle}</div>
              </button>
            ))}
          </div>
        </div>

        <div className="reports-card">
          <h2 className="reports-card-title">Recent Reports</h2>
          <div className="recent-report-list">
            {RECENT_REPORTS.map((report) => (
              <article key={report.title} className="recent-report-item">
                <div className="recent-report-header">
                  <h3>{report.title}</h3>
                  <span>{report.time}</span>
                </div>
                <p>{report.by}</p>
                <div className="recent-report-actions">
                  <button type="button" className="pill-btn">
                    View PDF
                  </button>
                  <button type="button" className="pill-btn">
                    View Excel
                  </button>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="reports-card">
        <h2 className="reports-card-title">Custom Report Builder</h2>
        <div className="custom-builder-grid">
          <div className="builder-field">
            <label htmlFor="report-type">Report Type</label>
            <select
              id="report-type"
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
            >
              <option>Sales Performance</option>
              <option>Expense Performance</option>
              <option>Pipeline Overview</option>
              <option>Team Performance</option>
              <option>Activity Summary</option>
            </select>
          </div>

          <div className="builder-field">
            <label htmlFor="time-period">Time Period</label>
            <select
              id="time-period"
              value={timePeriod}
              onChange={(e) => setTimePeriod(e.target.value)}
            >
              <option>This Week</option>
              <option>This Month</option>
              <option>Last Month</option>
              <option>This Quarter</option>
              <option>This Year</option>
            </select>
          </div>

          <div className="builder-field">
            <label htmlFor="format">Format</label>
            <select id="format" value={format} onChange={(e) => setFormat(e.target.value)}>
              <option>PDF</option>
              <option>Excel</option>
              <option>CSV</option>
            </select>
          </div>
        </div>

        <button type="button" className="primary-gradient-btn">
          Generate Custom Report
        </button>
      </section>
    </div>
  );
}

export default Reports;
